### ISSUE TITLE
Create New Contact fails

### ISSUE THREAD

**Issue by jojowork** [systopia/de.systopia.contactsource#7]
In CiviCRM 5.78.2 it is impossible to create a new contact with this extension.
No matter what I enter into the required fields campaign, information, first contact date, I get the following error message

`Bitte folgenden Fehler im unten stehenden Formular berichtigen:

    Kampagne ist ein Pflichtfeld.
    Information ist ein Pflichtfeld.
    First Contact Date ist ein Pflichtfeld.
`
Background: The newest CiviCRM-Version uses Formbuilder to build these forms.
But this extension seems to try to add the fields with the classic buildForm-Method.
https://github.com/systopia/de.systopia.contactsource/blob/master/CRM/Contactsource/ActivityCreation.php#L45

**Comment by jensschuppe** [comment]
*FormBuilder* is not involved, those were different forms.
